export {
  AnswerRequestSchema,
  AnswerResponseSchema,
  CitationSchema,
  CollectionJobPayloadSchema,
  ReplayJobPayloadSchema,
  CONTRACT_SCHEMA_VERSION,
  CONTRACT_VERSION,
  CoverageSchema,
  ErrorCodeSchema,
  ErrorEnvelopeSchema,
  ErrorSchema,
  HealthLiveResponseSchema,
  HealthReadyDependenciesSchema,
  HealthReadyResponseSchema,
  HealthStatusSchema,
  LicenseSchema,
  MetricTypeSchema,
  ObservationSchema,
  PageInfoSchema,
  ResolvedTimeRangeSchema,
  SourceDetailResponseSchema,
  SourceKeySchema,
  SourceListQuerySchema,
  SourceListResponseSchema,
  SourceStatusSchema,
  SourceSummarySchema,
  TimeRangeSchema,
  TopicListResponseSchema,
  TopicSearchQuerySchema,
  TopicSummarySchema,
  ValidationIssueSchema,
} from './schemas.js';

export type {
  AnswerRequest,
  AnswerResponse,
  Citation,
  CollectionJobPayload,
  ReplayJobPayload,
  ContractError,
  Coverage,
  ErrorCode,
  ErrorEnvelope,
  HealthLiveResponse,
  HealthReadyDependencies,
  HealthReadyResponse,
  HealthStatus,
  License,
  MetricType,
  Observation,
  PageInfo,
  ResolvedTimeRange,
  SourceDetailResponse,
  SourceKey,
  SourceListQuery,
  SourceListResponse,
  SourceStatus,
  SourceSummary,
  TimeRange,
  TopicListResponse,
  TopicSearchQuery,
  TopicSummary,
  ValidationIssue,
} from './schemas.js';

export {
  ContractValidationError,
  mapValidationFailureTo400,
  parseAnswerRequest,
  parseAnswerResponse,
  parseCollectionJobPayload,
  parseErrorEnvelope,
  parseHealthLiveResponse,
  parseHealthReadyResponse,
  parseReplayJobPayload,
  parseSourceDetailResponse,
  parseSourceListQuery,
  parseSourceListResponse,
  parseSourceSummary,
  parseTopicListResponse,
  parseTopicSearchQuery,
  parseTopicSummary,
  safeParseAnswerRequest,
  safeParseAnswerResponse,
  safeParseCollectionJobPayload,
  safeParseErrorEnvelope,
  safeParseHealthLiveResponse,
  safeParseHealthReadyResponse,
  safeParseReplayJobPayload,
  safeParseSourceDetailResponse,
  safeParseSourceListQuery,
  safeParseSourceListResponse,
  safeParseSourceSummary,
  safeParseTopicListResponse,
  safeParseTopicSearchQuery,
  safeParseTopicSummary,
  sanitizeAnswerResponse,
  sanitizeSourceDetailResponse,
  sanitizeSourceListResponse,
  sanitizeSourceSummary,
  sanitizeTopicListResponse,
  sanitizeTopicSummary,
} from './validation.js';
export type {
  BadRequestValidationResponse,
  SafeParseResult,
  ValidationFailure,
  ValidationSuccess,
} from './validation.js';

/** Marker retained for the initial workspace package boundary. */
export interface WorkspaceMarker {
  readonly package: '@techpulse/contracts';
}
