import type { SourceKey } from '@techpulse/contracts';
import type { SourcePolicy } from '@techpulse/domain';

/**
 * Authoritative source security & collection policies per SOURCE_CATALOG.md and SECURITY.md.
 */
export const SOURCE_POLICIES: Readonly<Record<SourceKey, SourcePolicy>> = {
  github_releases: {
    sourceKey: 'github_releases',
    allowedHosts: ['api.github.com'],
    allowedSchemes: ['https'],
    maxSizeBytes: 10 * 1024 * 1024, // 10MB
    maxRedirects: 3,
    verbatimOnly: false,
    defaultLicenseId: null, // repository-dependent
    piiFieldsToStrip: ['author', 'assets.uploader', 'user', 'owner'],
  },
  stack_exchange: {
    sourceKey: 'stack_exchange',
    allowedHosts: ['api.stackexchange.com'],
    allowedSchemes: ['https'],
    maxSizeBytes: 5 * 1024 * 1024,
    maxRedirects: 3,
    verbatimOnly: true,
    defaultLicenseId: 'CC-BY-SA-4.0',
    piiFieldsToStrip: ['owner'],
  },
  users_rust_lang: {
    sourceKey: 'users_rust_lang',
    allowedHosts: ['users.rust-lang.org'],
    allowedSchemes: ['https'],
    maxSizeBytes: 5 * 1024 * 1024,
    maxRedirects: 2,
    verbatimOnly: false,
    defaultLicenseId: 'MIT',
    piiFieldsToStrip: [
      'username',
      'name',
      'user_id',
      'avatar_template',
      'display_username',
      'last_poster_username',
      'post_stream.posts.username',
      'post_stream.posts.name',
      'post_stream.posts.user_id',
      'post_stream.posts.avatar_template',
      'post_stream.posts.display_username',
      'details.created_by.username',
      'details.created_by.name',
      'details.created_by.user_id',
      'details.created_by.avatar_template',
      'details.last_poster.username',
      'details.last_poster.name',
      'details.last_poster.user_id',
      'details.last_poster.avatar_template',
      'details.participants.username',
      'details.participants.name',
      'details.participants.user_id',
      'details.participants.avatar_template',
      'topic_list.topics.posters.user_id',
      'topic_list.topics.posters.description',
      'users.username',
      'users.name',
      'users.id',
      'users.avatar_template',
    ],
  },
  arxiv: {
    sourceKey: 'arxiv',
    allowedHosts: ['export.arxiv.org'],
    allowedSchemes: ['http', 'https'],
    maxSizeBytes: 10 * 1024 * 1024,
    maxRedirects: 2,
    verbatimOnly: false,
    defaultLicenseId: 'CC0-1.0',
    piiFieldsToStrip: ['authors.affiliation', 'authors.email'],
  },
  chrome_release_notes: {
    sourceKey: 'chrome_release_notes',
    allowedHosts: ['developer.chrome.com'],
    allowedSchemes: ['https'],
    maxSizeBytes: 5 * 1024 * 1024,
    maxRedirects: 3,
    verbatimOnly: false,
    defaultLicenseId: 'CC-BY-4.0',
    piiFieldsToStrip: [],
  },
  react_blog: {
    sourceKey: 'react_blog',
    allowedHosts: ['react.dev'],
    allowedSchemes: ['https'],
    maxSizeBytes: 5 * 1024 * 1024,
    maxRedirects: 3,
    verbatimOnly: false,
    defaultLicenseId: 'CC-BY-4.0',
    piiFieldsToStrip: [],
  },
  chrome_origin_trials: {
    sourceKey: 'chrome_origin_trials',
    allowedHosts: ['developer.chrome.com'],
    allowedSchemes: ['https'],
    maxSizeBytes: 10 * 1024 * 1024,
    maxRedirects: 3,
    verbatimOnly: false,
    defaultLicenseId: 'CC-BY-4.0',
    piiFieldsToStrip: [],
  },
  npm_registry: {
    sourceKey: 'npm_registry',
    allowedHosts: ['registry.npmjs.org'],
    allowedSchemes: ['https'],
    maxSizeBytes: 15 * 1024 * 1024,
    maxRedirects: 3,
    verbatimOnly: false,
    defaultLicenseId: null,
    piiFieldsToStrip: [
      'author.email',
      '_npmUser.email',
      'maintainers.email',
      'publisher.email',
      'contributors.email',
    ],
  },
  npm_downloads: {
    sourceKey: 'npm_downloads',
    allowedHosts: ['api.npmjs.org'],
    allowedSchemes: ['https'],
    maxSizeBytes: 2 * 1024 * 1024,
    maxRedirects: 2,
    verbatimOnly: false,
    defaultLicenseId: null,
    piiFieldsToStrip: [],
  },
  github_search: {
    sourceKey: 'github_search',
    allowedHosts: ['api.github.com'],
    allowedSchemes: ['https'],
    maxSizeBytes: 10 * 1024 * 1024,
    maxRedirects: 3,
    verbatimOnly: false,
    defaultLicenseId: null,
    piiFieldsToStrip: ['owner', 'user', 'milestone.creator', 'assignee', 'assignees'],
  },
  huggingface_hub: {
    sourceKey: 'huggingface_hub',
    allowedHosts: ['huggingface.co'],
    allowedSchemes: ['https'],
    maxSizeBytes: 5 * 1024 * 1024,
    maxRedirects: 3,
    verbatimOnly: false,
    defaultLicenseId: null,
    piiFieldsToStrip: ['author', 'maintainer'],
  },
};
